export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "HIDE_ALERT";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const UPDATE_HOUSE_BEGIN = 'UPDATE_HOUSE_BEGIN'
export const UPDATE_HOUSE_SUCCESS = 'UPDATE_HOUSE_SUCCESS'
export const UPDATE_HOUSE_ERROR = 'UPDATE_HOUSE_ERROR'

export const UPDATE_BUSINESS_BEGIN = 'UPDATE_BUSINESS_BEGIN'
export const UPDATE_BUSINESS_SUCCESS = 'UPDATE_BUSINESS_SUCCESS'
export const UPDATE_BUSINESS_ERROR = 'UPDATE_BUSINESS_ERROR'

export const UPDATE_SALARY_BEGIN = 'UPDATE_SALARY_BEGIN'
export const UPDATE_SALARY_SUCCESS = 'UPDATE_SALARY_SUCCESS'
export const UPDATE_SALARY_ERROR = 'UPDATE_SALARY_ERROR'


export const UPDATE_INVESTMENT_BEGIN = 'UPDATE_INVESTMENT_BEGIN'
export const UPDATE_INVESTMENT_SUCCESS = 'UPDATE_INVESTMENT_SUCCESS'
export const UPDATE_INVESTMENT_ERROR = 'UPDATE_INVESTMENT_ERROR'

export const SAVE_QA_BEGIN= 'SAVE_QA_BEGIN'
export const SAVE_QA_SUCCESS = 'SAVE_QA_SUCCESS'
export const SAVE_QA_ERROR = 'SAVE_QA_ERROR'



export const GET_MSG_BEGIN= 'GET_MSG_BEGIN'
export const GET_MSG_SUCCESS = 'GET_MSG_SUCCESS'
export const GET_MSG_ERROR = 'GET_MSG_ERROR'
export const SET_CONSULTING = 'SET_CONSULTING'
export const RESET_CONSULTING = 'RESET_CONSULTING'

